apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-app

resources:
- ../../base

images:
- name: phanle1010/platform-app
  newTag: 31cd2b074c97ee6bc3ab5f25ab941a3372e47d00

patches:
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: platform-app-config

commonLabels:
  environment: staging
